### ISSUE TITLE
Versioning of ANTLR

### ISSUE THREAD

**Issue by jonnybluesman** [andreamust/TPSD#2]
Got versioning issues with version 4.10 (which is installed when using `~=` instead of `==`).
https://github.com/andreamust/TPSD/blob/aa2bd70fb0439c9bea6cac949bb2fc555b187245/requirements.txt#L3

Can be easily solved if requesting ==4.7 but it still not clear why this happens.

**Comment by andreamust** [comment]
I've had the same issue. 

Planning to switch to another chord converter, as documented in #3

**Comment by andreamust** [comment]
The chord parser has been removed and reimplemented using the harte-library in 72ec89522a729971695432b8c20b05da3cd845d3
