### ISSUE TITLE
Renaming the src folder with tpsd

### ISSUE THREAD

**Issue by jonnybluesman** [andreamust/TPSD#4]
We should consider some renaming if we are reusing this in other projects and not just for reproducibility. Ideally, the root folder with the code could be `tpsd` so that we can import modules consistently.

**Comment by andreamust** [comment]
`src` folder renamed in `tpsd` in https://github.com/andreamust/TPSD/commit/ef1b04737e007deedd2c33099ed9804c9c4a8830
